spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:cadastro;MODE=MySQL;
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: false
        format_sql: true